### ISSUE TITLE
Next articles carousel doesn't scroll

### ISSUE THREAD

**Issue by Poliuk** [worona/saturn-app-theme-worona#110]
It's impossible to scroll and see the rest of "next articles".

**Comment by DAreRodz** [comment]
Momentum scrolling is not working as explained in an [open issue](https://github.com/oliviertassinari/react-swipeable-views/issues/257) in [react-swipeable-views](https://github.com/oliviertassinari/react-swipeable-views). We have to wait for that issue to be resolved. In the mean time, the `-webkit-overflow-scrolling` property will be set to `auto` instead of `touch`.
